"""Add a additional info about User

Revision ID: 376b47475b31
Revises: 4223889553a1
Create Date: 2019-11-10 10:38:09.510949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376b47475b31'
down_revision = '4223889553a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
